In [1]:
import numpy as np
import pandas as pd
pd.options.display.max_columns=20 #DataFrameの表示の際に、最大20列まで表示
pd.options.display.max_rows=20     #DataFrameの表示の際に、最大20行まで表示
pd.options.display.max_colwidth=80 #1つのセルに表示される文字数を最大80文字に制限
np.set_printoptions(precision=4,suppress=True) #小数点以下4桁まで表示かつ非常に小さい数を指数表記(e-05 とか)にしない

In [2]:
from pandas import Series,DataFrame

In [3]:
obj=pd.Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2=pd.Series([4,7,-5,3],index=["d","b","a","c"])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2["a"]

np.int64(-5)

In [12]:
obj2["d"]=6

In [13]:
obj2[["c","a","d"]]

c    3
a   -5
d    6
dtype: int64

In [14]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [15]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [16]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
"b" in obj2

True

In [18]:
"e" in obj2

False

In [19]:
sdata={"Ohio":35000,"Texas":71000,"Oregon":16000,"Utah":5000}

In [20]:
obj3=pd.Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [23]:
states=["California","Ohio","Oregon","Texas"]

In [24]:
obj4=pd.Series(sdata,index=states)

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [28]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [32]:
obj4.name="population"

In [35]:
obj4.index.name="state"

In [36]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [37]:
obj

state
0    4
1    7
2   -5
3    3
dtype: int64

In [41]:
obj=pd.Series([4,7,-5,3])

In [42]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [43]:
obj.index=["Bob","Steve","Jeff","Ryan"]

In [44]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [45]:
data={"state":["Ohio","Ohio","Ohio","Nevada","Nevada","Nevada"],
     "year":[2000,2001,2002,2001,2002,2003],
     "pop":[1.5,1.7,3.6,2.4,2.9,3.2]}

In [48]:
frame=pd.DataFrame(data)

In [49]:
frame

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [50]:
frame.head()

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9


In [51]:
frame.tail()

,state,year,pop
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


In [52]:
pd.DataFrame(data,columns=["year","state","pop"])

,year,state,pop
0,2000,Ohio,1.5
1,2001,Ohio,1.7
2,2002,Ohio,3.6
3,2001,Nevada,2.4
4,2002,Nevada,2.9
5,2003,Nevada,3.2


In [53]:
frame2=pd.DataFrame(data,columns=["year","state","pop","debt"])

In [54]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,NaN
1,2001,Ohio,1.7,NaN
2,2002,Ohio,3.6,NaN
3,2001,Nevada,2.4,NaN
4,2002,Nevada,2.9,NaN
5,2003,Nevada,3.2,NaN


In [55]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [56]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [57]:
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [58]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [59]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [60]:
frame2["debt"]=16.5

In [61]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,16.5
1,2001,Ohio,1.7,16.5
2,2002,Ohio,3.6,16.5
3,2001,Nevada,2.4,16.5
4,2002,Nevada,2.9,16.5
5,2003,Nevada,3.2,16.5


In [62]:
frame2["debt"]=np.arange(6.)

In [63]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,0.0
1,2001,Ohio,1.7,1.0
2,2002,Ohio,3.6,2.0
3,2001,Nevada,2.4,3.0
4,2002,Nevada,2.9,4.0
5,2003,Nevada,3.2,5.0


In [64]:
val=pd.Series([-1.2,-1.5,-1.7],index=["two","four","five"])

In [65]:
frame2["debt"]=val

In [66]:
frame2

,year,state,pop,debt
0,2000,Ohio,1.5,NaN
1,2001,Ohio,1.7,NaN
2,2002,Ohio,3.6,NaN
3,2001,Nevada,2.4,NaN
4,2002,Nevada,2.9,NaN
5,2003,Nevada,3.2,NaN


In [67]:
frame2["eastern"]=frame2["state"]=="Ohio"

In [68]:
frame2

,year,state,pop,debt,eastern
0,2000,Ohio,1.5,NaN,True
1,2001,Ohio,1.7,NaN,True
2,2002,Ohio,3.6,NaN,True
3,2001,Nevada,2.4,NaN,False
4,2002,Nevada,2.9,NaN,False
5,2003,Nevada,3.2,NaN,False


In [69]:
del frame2["eastern"]

In [70]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [71]:
population={"Ohio":{2000:1.5,2001:1.7,2002:3.6},
           "Nevada":{2001:2.4,2002:2.9}}

In [72]:
frame3=pd.DataFrame(population)

In [73]:
frame3

,Ohio,Nevada
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [74]:
frame3.T

,2000,2001,2002
Ohio,1.5,1.7,3.6
Nevada,NaN,2.4,2.9


In [75]:
pd.DataFrame(population,index=[2001,2002,2003])

,Ohio,Nevada
2001,1.7,2.4
2002,3.6,2.9
2003,NaN,NaN


In [76]:
pdata={"Ohio":frame3["Ohio"][:-1],
      "Nevada":frame3["Nevada"][:2]}

In [77]:
pd.DataFrame(pdata)

,Ohio,Nevada
2000,1.5,NaN
2001,1.7,2.4


In [78]:
frame3.index.name="year"

In [79]:
frame3.columns.name="state"

In [80]:
frame3

state,Ohio,Nevada
year,,
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [81]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [82]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [83]:
obj=pd.Series(np.arange(3),index=["a","b","c"])

In [84]:
index=obj.index

In [85]:
index

Index(['a', 'b', 'c'], dtype='object')

In [86]:
index[1:]

Index(['b', 'c'], dtype='object')

In [88]:
#index[1]="d" はできない　つまり不変

In [89]:
labels=pd.Index(np.arange(3))

In [90]:
labels

Index([0, 1, 2], dtype='int64')

In [94]:
obj2=pd.Series([1.5,-2.5,0],index=labels)

In [95]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [96]:
obj2.index is labels

True

In [97]:
frame3

state,Ohio,Nevada
year,,
2000,1.5,NaN
2001,1.7,2.4
2002,3.6,2.9


In [98]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [99]:
"Ohio" in frame3.columns

True

In [100]:
2003 in frame3.index

False

In [101]:
pd.Index(["foo","foo","bar","bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [103]:
idx1 = pd.Index(["a", "b"])
idx2 = pd.Index(["c"])
idx1.append(idx2)   # Index(['a','b','c'])

Index(['a', 'b', 'c'], dtype='object')

In [104]:
idx1 = pd.Index(["a","b","c"])
idx2 = pd.Index(["b","d"])
idx1.difference(idx2)   # Index(['a','c'])


Index(['a', 'c'], dtype='object')

In [105]:
idx1.intersection(idx2)   # Index(['b'])


Index(['b'], dtype='object')

In [106]:
idx1.union(idx2)   # Index(['a','b','c','d'])


Index(['a', 'b', 'c', 'd'], dtype='object')

In [107]:
idx = pd.Index(["a","b","c"])
idx.isin(["b","c"])   # array([False, True, True])


array([False,  True,  True])

In [108]:
idx = pd.Index(["a","b","c"])
idx.delete(1)   # Index(['a','c'])


Index(['a', 'c'], dtype='object')

In [109]:
idx.drop("b")   # Index(['a','c'])


Index(['a', 'c'], dtype='object')

In [110]:
idx.insert(1, "x")   # Index(['a','x','b','c'])


Index(['a', 'x', 'b', 'c'], dtype='object')

In [113]:
pd.Index([1,2,3]).is_monotonic_increasing

True

In [114]:
pd.Index([3,2,1]).is_monotonic_decreasing

True

In [115]:
pd.Index([1,3,2]).is_monotonic_increasing

False

In [116]:
pd.Index(["a","b","c"]).is_unique

True

In [118]:
pd.Index(["a","a","b"]).is_unique

False

In [119]:
pd.Index(["a","a","b","c","c"]).unique()

Index(['a', 'b', 'c'], dtype='object')

In [120]:
obj=pd.Series([4.5,7.2,-5.3,3.6],index=["d","b","a","c"])

In [121]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [123]:
obj2=obj.reindex(["a","b","c","d","e"])

In [124]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [125]:
obj3=pd.Series(["blue","purple","yellow"],index=[0,2,4])

In [126]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [127]:
obj3.reindex(np.arange(6),method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [128]:
frame=pd.DataFrame(np.arange(9).reshape((3,3)),
                   index=["a","c","d"],
                  columns=["Ohio","Texas","California"])

In [129]:
frame

,Ohio,Texas,California
a,0,1,2
c,3,4,5
d,6,7,8


In [130]:
frame2=frame.reindex(index=["a","b","c","d"])

In [131]:
frame2

,Ohio,Texas,California
a,0.0,1.0,2.0
b,NaN,NaN,NaN
c,3.0,4.0,5.0
d,6.0,7.0,8.0


In [132]:
states=["Texas","Utah","California"]

In [133]:
frame.reindex(columns=states)

,Texas,Utah,California
a,1,NaN,2
c,4,NaN,5
d,7,NaN,8


In [134]:
frame.reindex(states,axis="columns")

,Texas,Utah,California
a,1,NaN,2
c,4,NaN,5
d,7,NaN,8


In [137]:
frame.reindex(labels=["d","c","a"])

,Ohio,Texas,California
d,6,7,8
c,3,4,5
a,0,1,2


In [139]:
frame.reindex(index=["d","c","a"])

,Ohio,Texas,California
d,6,7,8
c,3,4,5
a,0,1,2


In [140]:
frame.reindex(columns=["Ohio","Japan","Nevada"])

,Ohio,Japan,Nevada
a,0,NaN,NaN
c,3,NaN,NaN
d,6,NaN,NaN


In [141]:
frame.reindex(["d","c","a"],axis="index")

,Ohio,Texas,California
d,6,7,8
c,3,4,5
a,0,1,2


In [144]:
frame.reindex(["a","b","c","d"],method="ffill") #前のデータで欠損を埋める

,Ohio,Texas,California
a,0,1,2
b,0,1,2
c,3,4,5
d,6,7,8


In [145]:
frame.reindex(["a","b","c","d"],method="bfill") #後のデータで欠損を埋める

,Ohio,Texas,California
a,0,1,2
b,3,4,5
c,3,4,5
d,6,7,8


In [146]:
frame.reindex(index=["a","b","c","d"],fill_value=0)

,Ohio,Texas,California
a,0,1,2
b,0,0,0
c,3,4,5
d,6,7,8


In [149]:
frame.reindex(["a","b","c","d","e","f"],method="ffill",limit=1)
#limitは欠損を埋める際、連続して埋める個数を制限する

,Ohio,Texas,California
a,0.0,1.0,2.0
b,0.0,1.0,2.0
c,3.0,4.0,5.0
d,6.0,7.0,8.0
e,6.0,7.0,8.0
f,NaN,NaN,NaN


In [155]:
#frame.reindex([1,1.5],method="nearest",tolerance=1)
#欠損を埋める際、インデックスの数値がどのくらいまでの時に埋めるかを
#toleranceは制限する

In [157]:
frame.reindex(index=["a", "b"], level=0)
#層階型インデックスに対して、再インデックスを行う層を指定する

,Ohio,Texas,California
a,0.0,1.0,2.0
b,NaN,NaN,NaN


In [164]:
frame2 = frame.reindex(["a","c","d"] ,copy=True)
frame2

,Ohio,Texas,California
a,0,1,2
c,3,4,5
d,6,7,8


In [165]:
frame==frame2

,Ohio,Texas,California
a,True,True,True
c,True,True,True
d,True,True,True


In [166]:
frame2=frame.reindex(["a","c","d"],copy=False)
frame2

,Ohio,Texas,California
a,0,1,2
c,3,4,5
d,6,7,8


In [167]:
frame==frame2

,Ohio,Texas,California
a,True,True,True
c,True,True,True
d,True,True,True


In [169]:
frame.loc[["a","d","c"],["California","Texas"]]

,California,Texas
a,2,1
d,8,7
c,5,4


In [170]:
obj=pd.Series(np.arange(5.),index=["a","b","c","d","e"])

In [171]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [172]:
new_obj=obj.drop("c")

In [173]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [174]:
obj.drop(["d","c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [175]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                 index=["Ohio","Colorado","Utah","New York"],
                 columns=["one","two","three","four"])

In [176]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [177]:
data.drop(index=["Colorado","Ohio"])

,one,two,three,four
Utah,8,9,10,11
New York,12,13,14,15


In [178]:
data.drop("two",axis=1)

,one,three,four
Ohio,0,2,3
Colorado,4,6,7
Utah,8,10,11
New York,12,14,15


In [179]:
data.drop(["two","four"],axis="columns")

,one,three
Ohio,0,2
Colorado,4,6
Utah,8,10
New York,12,14


In [180]:
obj=pd.Series(np.arange(4.),index=["a","b","c","d"])

In [181]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [182]:
obj["b"]

np.float64(1.0)

In [183]:
obj[1]

C:\Users\sansp\AppData\Local\Temp\ipykernel_3924\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


np.float64(1.0)

In [184]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [185]:
obj[["b","a","d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [186]:
obj[[1,3]]

C:\Users\sansp\AppData\Local\Temp\ipykernel_3924\1781339481.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1,3]]


b    1.0
d    3.0
dtype: float64

In [187]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [188]:
obj.loc[["b","a","d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [189]:
obj1=pd.Series([1,2,3],index=[2,0,1])

In [190]:
obj2=pd.Series([1,2,3],index=["a","b","c"])

In [191]:
obj1

2    1
0    2
1    3
dtype: int64

In [192]:
obj2

a    1
b    2
c    3
dtype: int64

In [195]:
obj1[[0,1,2]] #これは指定された数字の行を表示

0    2
1    3
2    1
dtype: int64

In [196]:
obj2[[0,1,2]] #これは指定された行数の行を表示

C:\Users\sansp\AppData\Local\Temp\ipykernel_3924\3291135758.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0,1,2]] #これは指定された行数の行を表示


a    1
b    2
c    3
dtype: int64

In [197]:
#obj2.loc[[0,1]]
#これはlocは、indexが整数でないときに使うとエラーが出る

In [200]:
obj1.iloc[[0,1,2]] #ilocは何が何でも指定された行数の行を表示

2    1
0    2
1    3
dtype: int64

In [201]:
obj2.iloc[[0,1,2]]

a    1
b    2
c    3
dtype: int64

In [203]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [204]:
obj2.loc["b":"c"]=5

In [205]:
obj2

a    1
b    5
c    5
dtype: int64

In [206]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                 index=["Ohio","Colorado","Utah","New York"],
                 columns=["one","two","three","four"])

In [207]:
data

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [208]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [209]:
data[["three","one"]]

,three,one
Ohio,2,0
Colorado,6,4
Utah,10,8
New York,14,12


In [210]:
data[:2]

,one,two,three,four
Ohio,0,1,2,3
Colorado,4,5,6,7


In [212]:
data[data["three"]>5]

,one,two,three,four
Colorado,4,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [213]:
data<5

,one,two,three,four
Ohio,True,True,True,True
Colorado,True,False,False,False
Utah,False,False,False,False
New York,False,False,False,False


In [214]:
data[data<5]=0

In [215]:
data

,one,two,three,four
Ohio,0,0,0,0
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [216]:
data

,one,two,three,four
Ohio,0,0,0,0
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [217]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [218]:
data.loc[["Colorado","New York"]]

,one,two,three,four
Colorado,0,5,6,7
New York,12,13,14,15


In [220]:
data.loc["Colorado",["two","three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [221]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [222]:
data.iloc[[2,1]]

,one,two,three,four
Utah,8,9,10,11
Colorado,0,5,6,7


In [223]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [224]:
data.iloc[[1,2],[3,0,1]]

,four,one,two
Colorado,7,0,5
Utah,11,8,9


In [225]:
data.loc[:"Utah","two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [226]:
data.iloc[:,:3][data.three>5]

,one,two,three
Colorado,0,5,6
Utah,8,9,10
New York,12,13,14


In [227]:
data.loc[data.three>=2]

,one,two,three,four
Colorado,0,5,6,7
Utah,8,9,10,11
New York,12,13,14,15


In [229]:
data["two"]

Ohio         0
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [230]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [231]:
data.loc[:,"two"]

Ohio         0
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [232]:
data.loc["Colorado","two"]

np.int64(5)

In [234]:
data.iloc[1]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [235]:
data.iloc[:,1]

Ohio         0
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [236]:
data.iloc[1,1]

np.int64(5)

In [238]:
data.at["Colorado","two"]

np.int64(5)

In [239]:
data.iat[1,1]

np.int64(5)

In [240]:
ser=pd.Series(np.arange(3.))

In [241]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [245]:
#ser[-1]

#これだとエラーが出る
#indexが整数とかの場合、こういう風にすると
#ラベルベースで参照したいのか位置ベースで参照したいのか分からなくなる

In [246]:
ser2=pd.Series(np.arange(3.),index=["a","b","c"])

In [248]:
ser2[-1]
#indexが文字の場合、ラベルベースで参照したいわけないとわかるので
#ちゃんと値が返ってくる

C:\Users\sansp\AppData\Local\Temp\ipykernel_3924\3251775948.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]


np.float64(2.0)

In [249]:
ser.iloc[-1]

np.float64(2.0)

In [250]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [251]:
data.loc[:,"one"]=1

In [252]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,1,5,6,7
Utah,1,9,10,11
New York,1,13,14,15


In [253]:
data.iloc[2]=5

In [254]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,1,5,6,7
Utah,5,5,5,5
New York,1,13,14,15


In [255]:
data.loc[data["four"]>5]=3

In [256]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,3,3,3,3
Utah,5,5,5,5
New York,3,3,3,3


In [257]:
data.loc[data.three==5]["three"]=6

C:\Users\sansp\AppData\Local\Temp\ipykernel_3924\3936912511.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data.three==5]["three"]=6


In [258]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,3,3,3,3
Utah,5,5,5,5
New York,3,3,3,3


In [259]:
data.loc[data.three==5,"three"]=6

In [260]:
data

,one,two,three,four
Ohio,1,0,0,0
Colorado,3,3,3,3
Utah,5,5,6,5
New York,3,3,3,3


In [261]:
s1=pd.Series([7.3,-2.5,3.4,1.5],index=["a","c","d","e"])

In [262]:
s2=pd.Series([-2.1,3.6,-1.5,4,3.1],index=["a","c","e","f","g"])

In [263]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [264]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [265]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [266]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),
                columns=list("bcd"),
                index=["Ohio","Texas","Colorado"])

In [267]:
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),
                columns=list("bde"),
                index=["Utah","Ohio","Texas","Oregon"])

In [268]:
df1

,b,c,d
Ohio,0.0,1.0,2.0
Texas,3.0,4.0,5.0
Colorado,6.0,7.0,8.0


In [269]:
df2

,b,d,e
Utah,0.0,1.0,2.0
Ohio,3.0,4.0,5.0
Texas,6.0,7.0,8.0
Oregon,9.0,10.0,11.0


In [270]:
df1+df2

,b,c,d,e
Colorado,NaN,NaN,NaN,NaN
Ohio,3.0,NaN,6.0,NaN
Oregon,NaN,NaN,NaN,NaN
Texas,9.0,NaN,12.0,NaN
Utah,NaN,NaN,NaN,NaN


In [273]:
df1=pd.DataFrame({"A":[1,2]})

In [274]:
df2=pd.DataFrame({"B":[3,4]})

In [275]:
df1

,A
0,1
1,2


In [276]:
df2

,B
0,3
1,4


In [277]:
df1+df2

,A,B
0,NaN,NaN
1,NaN,NaN


In [278]:
df1=pd.DataFrame(np.arange(12.).reshape((3,4)),
                columns=list("abcd"))

In [279]:
df2=pd.DataFrame(np.arange(20.).reshape((4,5)),
                columns=list("abcde"))

In [280]:
df2.loc[1,"b"]=np.nan

In [281]:
df1

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [282]:
df2

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,4.0
1,5.0,NaN,7.0,8.0,9.0
2,10.0,11.0,12.0,13.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [283]:
df1+df2

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,NaN
1,9.0,NaN,13.0,15.0,NaN
2,18.0,20.0,22.0,24.0,NaN
3,NaN,NaN,NaN,NaN,NaN


In [284]:
df1.add(df2,fill_value=0)

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,4.0
1,9.0,5.0,13.0,15.0,9.0
2,18.0,20.0,22.0,24.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [285]:
1/df1

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [286]:
df1.rdiv(1)

,a,b,c,d
0,inf,1.000000,0.500000,0.333333
1,0.250,0.200000,0.166667,0.142857
2,0.125,0.111111,0.100000,0.090909


In [287]:
df1.reindex(columns=df2.columns,fill_value=0)

,a,b,c,d,e
0,0.0,1.0,2.0,3.0,0
1,4.0,5.0,6.0,7.0,0
2,8.0,9.0,10.0,11.0,0


In [288]:
df1.radd(df2,fill_value=0)

,a,b,c,d,e
0,0.0,2.0,4.0,6.0,4.0
1,9.0,5.0,13.0,15.0,9.0
2,18.0,20.0,22.0,24.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [289]:
df1.sub(df2,fill_value=0)

,a,b,c,d,e
0,0.0,0.0,0.0,0.0,-4.0
1,-1.0,5.0,-1.0,-1.0,-9.0
2,-2.0,-2.0,-2.0,-2.0,-14.0
3,-15.0,-16.0,-17.0,-18.0,-19.0


In [290]:
df1.rsub(df2,fill_value=0)

,a,b,c,d,e
0,0.0,0.0,0.0,0.0,4.0
1,1.0,-5.0,1.0,1.0,9.0
2,2.0,2.0,2.0,2.0,14.0
3,15.0,16.0,17.0,18.0,19.0


In [291]:
df1.floordiv(1)

,a,b,c,d
0,0.0,1.0,2.0,3.0
1,4.0,5.0,6.0,7.0
2,8.0,9.0,10.0,11.0


In [292]:
df1.rfloordiv(1)

,a,b,c,d
0,inf,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0


In [297]:
df1.mul(df2,fill_value=0)

,a,b,c,d,e
0,0.0,1.0,4.0,9.0,0.0
1,20.0,0.0,42.0,56.0,0.0
2,80.0,99.0,120.0,143.0,0.0
3,0.0,0.0,0.0,0.0,0.0


In [298]:
df1.rmul(df2,fill_value=0)

,a,b,c,d,e
0,0.0,1.0,4.0,9.0,0.0
1,20.0,0.0,42.0,56.0,0.0
2,80.0,99.0,120.0,143.0,0.0
3,0.0,0.0,0.0,0.0,0.0


In [299]:
df1.pow(2)

,a,b,c,d
0,0.0,1.0,4.0,9.0
1,16.0,25.0,36.0,49.0
2,64.0,81.0,100.0,121.0


In [300]:
df1.rpow(2)

,a,b,c,d
0,1.0,2.0,4.0,8.0
1,16.0,32.0,64.0,128.0
2,256.0,512.0,1024.0,2048.0


In [301]:
arr=np.arange(12.).reshape((3,4))

In [302]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [303]:
arr[0]

array([0., 1., 2., 3.])

In [304]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [305]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),
                  columns=list("bde"),
                  index=["Utah","Ohio","Texas","Oregon"])

In [306]:
series=frame.iloc[0]

In [307]:
frame

,b,d,e
Utah,0,1,2
Ohio,3,4,5
Texas,6,7,8
Oregon,9,10,11


In [308]:
series

b    0
d    1
e    2
Name: Utah, dtype: int64

In [309]:
frame-series

,b,d,e
Utah,0,0,0
Ohio,3,3,3
Texas,6,6,6
Oregon,9,9,9


In [310]:
series2=pd.Series(np.arange(3),index=["b","e","f"])

In [311]:
series2

b    0
e    1
f    2
dtype: int64

In [312]:
frame+series2

,b,d,e,f
Utah,0.0,NaN,3.0,NaN
Ohio,3.0,NaN,6.0,NaN
Texas,6.0,NaN,9.0,NaN
Oregon,9.0,NaN,12.0,NaN


In [313]:
series3=frame["d"]

In [314]:
frame

,b,d,e
Utah,0,1,2
Ohio,3,4,5
Texas,6,7,8
Oregon,9,10,11


In [315]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int64

In [318]:
frame.sub(series3,axis="index")

,b,d,e
Utah,-1,0,1
Ohio,-1,0,1
Texas,-1,0,1
Oregon,-1,0,1


In [319]:
frame=pd.DataFrame(np.random.standard_normal((4,3)),
                  columns=list("bde"),
                  index=["Utah","Ohio","Texas","Oregon"])

In [320]:
frame

,b,d,e
Utah,1.366144,0.050145,-2.270392
Ohio,-0.349093,0.093060,0.299592
Texas,-0.267775,2.512054,0.044665
Oregon,0.907197,2.092693,-1.094376


In [321]:
np.abs(frame)

,b,d,e
Utah,1.366144,0.050145,2.270392
Ohio,0.349093,0.093060,0.299592
Texas,0.267775,2.512054,0.044665
Oregon,0.907197,2.092693,1.094376


In [322]:
def f1(x):
    return x.max()-x.min()

In [323]:
frame.apply(f1)

b    1.715236
d    2.461909
e    2.569984
dtype: float64

In [324]:
frame.apply(f1,axis="columns")

Utah      3.636536
Ohio      0.648685
Texas     2.779830
Oregon    3.187069
dtype: float64

In [325]:
def f2(x):
    return pd.Series([x.min(),x.max()],index=["min","max"])

In [326]:
frame.apply(f2)

,b,d,e
min,-0.349093,0.050145,-2.270392
max,1.366144,2.512054,0.299592


In [327]:
def my_format(x):
    return f"{x:.2f}"

In [329]:
frame.map(my_format)

,b,d,e
Utah,1.37,0.05,-2.27
Ohio,-0.35,0.09,0.30
Texas,-0.27,2.51,0.04
Oregon,0.91,2.09,-1.09


In [330]:
frame["e"].map(my_format)

Utah      -2.27
Ohio       0.30
Texas      0.04
Oregon    -1.09
Name: e, dtype: object

In [331]:
obj=pd.Series(np.arange(4),index=["d","a","b","c"])

In [332]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [333]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [334]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),
                  index=["three","one"],
                  columns=["d","a","b","c"])

In [335]:
frame

,d,a,b,c
three,0,1,2,3
one,4,5,6,7


In [336]:
frame.sort_index()

,d,a,b,c
one,4,5,6,7
three,0,1,2,3


In [337]:
frame.sort_index(axis="columns")

,a,b,c,d
three,1,2,3,0
one,5,6,7,4


In [338]:
frame.sort_index(axis="columns",ascending=False)

,d,c,b,a
three,0,3,2,1
one,4,7,6,5


In [339]:
obj=pd.Series([4,7,-3,2])

In [340]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [341]:
obj=pd.Series([4,np.nan,7,np.nan,-3,2])

In [342]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [343]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [344]:
frame=pd.DataFrame({"b":[4,7,-3,2],"a":[0,1,0,1]})

In [345]:
frame

,b,a
0,4,0
1,7,1
2,-3,0
3,2,1


In [346]:
frame.sort_values("b")

,b,a
2,-3,0
3,2,1
0,4,0
1,7,1


In [348]:
frame.sort_values(["a","b"])
#まず列aでソートし、その中で被ったどうしで列bでソート

,b,a
2,-3,0
0,4,0
3,2,1
1,7,1


In [349]:
obj=pd.Series([7,-5,7,4,2,0,4])

In [350]:
obj.rank()
#順位が被ったらその平均の順位が出力される

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [353]:
obj.rank(method="first")
#タイの場合indexが若い方が順位が上

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [354]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [355]:
frame=pd.DataFrame({"b":[4.3,7,-3,2],"a":[0,1,0,1],
                    "c":[-2,5,8,-2.5]})

In [356]:
frame

,b,a,c
0,4.3,0,-2.0
1,7.0,1,5.0
2,-3.0,0,8.0
3,2.0,1,-2.5


In [357]:
frame.rank(axis="columns")

,b,a,c
0,3.0,2.0,1.0
1,3.0,1.0,2.0
2,1.0,2.0,3.0
3,3.0,2.0,1.0


In [358]:
frame.rank()

,b,a,c
0,3.0,1.5,2.0
1,4.0,3.5,3.0
2,1.0,1.5,4.0
3,2.0,3.5,1.0


In [362]:
frame.rank(method="min")
#タイなら順位が最小の方に合わせる

,b,a,c
0,3.0,1.0,2.0
1,4.0,3.0,3.0
2,1.0,1.0,4.0
3,2.0,3.0,1.0


In [364]:
frame.rank(method="max")
#タイなら順位が最大の方に合わせる

,b,a,c
0,3.0,2.0,2.0
1,4.0,4.0,3.0
2,1.0,2.0,4.0
3,2.0,4.0,1.0


In [365]:
frame.rank(method="dense")
#被りをすべて消して順位づけした時の順位をタイのものにも振り分け

,b,a,c
0,3.0,1.0,2.0
1,4.0,2.0,3.0
2,1.0,1.0,4.0
3,2.0,2.0,1.0


In [366]:
obj=pd.Series(np.arange(5),index=["a","a","b","b","c"])

In [367]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [368]:
obj.index.is_unique

False

In [369]:
obj["a"]

a    0
a    1
dtype: int64

In [370]:
obj["c"]

np.int64(4)

In [371]:
df=pd.DataFrame(np.random.standard_normal((5,3)),
               index=["a","a","b","b","c"])

In [372]:
df

,0,1,2
a,-0.002034,-2.409790,-0.194282
a,-0.322007,-1.946029,0.583536
b,-0.369020,-0.698198,-1.930997
b,-0.027648,-0.189807,0.674784
c,0.531298,0.999769,0.575120


In [373]:
df.loc["b"]

,0,1,2
b,-0.369020,-0.698198,-1.930997
b,-0.027648,-0.189807,0.674784


In [374]:
df.loc["c"]

0    0.531298
1    0.999769
2    0.575120
Name: c, dtype: float64

In [376]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],
                 [0.75,-1.3]],
               index=["a","b","c","d"],
               columns=["one","two"])

In [377]:
df

,one,two
a,1.40,NaN
b,7.10,-4.5
c,NaN,NaN
d,0.75,-1.3


In [378]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [379]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [380]:
df.sum(axis="index",skipna=False)

one   NaN
two   NaN
dtype: float64

In [381]:
df.sum(axis="columns",skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [382]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [383]:
df.idxmax()

one    b
two    d
dtype: object

In [385]:
df.idxmin()

one    d
two    b
dtype: object

In [386]:
df.cumsum()

,one,two
a,1.40,NaN
b,8.50,-4.5
c,NaN,NaN
d,9.25,-5.8


In [387]:
df.describe()

,one,two
count,3.000000,2.000000
mean,3.083333,-2.900000
std,3.493685,2.262742
min,0.750000,-4.500000
25%,1.075000,-3.700000
50%,1.400000,-2.900000
75%,4.250000,-2.100000
max,7.100000,-1.300000


In [388]:
obj=pd.Series(["a","a","b","c"]*4)

In [389]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [391]:
df.count() #NAでない数

one    3
two    2
dtype: int64

In [395]:
df.loc[:,"one"].argmin()
#argmin,argmaxはデータフレームでは使えない

np.int64(3)

In [397]:
df.quantile()
#データのパーセンタイル(分位点)を出す

one    1.4
two   -2.9
Name: 0.5, dtype: float64

In [398]:
df.median()

one    1.4
two   -2.9
dtype: float64

In [404]:
df.prod()
#すべての値の積

one    7.455
two    5.850
dtype: float64

In [405]:
df.var()

one    12.205833
two     5.120000
dtype: float64

In [406]:
df.std()

one    3.493685
two    2.262742
dtype: float64

In [410]:
df.skew()
#標本の分布がどちらに歪んでるかの歪度を出力する
#０より大きいと右に歪み、０より小さいと左に歪んでいる
#データ数が2以下だとNaN

one    1.664846
two         NaN
dtype: float64

In [413]:
df.kurt()
#標本の分布がどれだけ尖っているかの尖度を出力する
#０より大きいと尖っていて裾が重く、０より小さいと平べったくなる
#データ数が3以下だとNaN

one   NaN
two   NaN
dtype: float64

In [417]:
df.cummin() #累積の最小値　最小値を更新していく

,one,two
a,1.40,NaN
b,1.40,-4.5
c,NaN,NaN
d,0.75,-4.5


In [418]:
df.cummax() #累積の最大値　最大値を更新していく

,one,two
a,1.4,NaN
b,7.1,-4.5
c,NaN,NaN
d,7.1,-1.3


In [419]:
df.cumprod() #累積の積

,one,two
a,1.400,NaN
b,9.940,-4.50
c,NaN,NaN
d,7.455,5.85


In [421]:
df.pct_change() #前の値からどのくらい変化したかをパーセンテージで出力

C:\Users\sansp\AppData\Local\Temp\ipykernel_3924\2566114270.py:1: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  df.pct_change() #前の値からどのくらい変化したかをパーセンテージで出力


,one,two
a,NaN,NaN
b,4.071429,NaN
c,0.000000,0.000000
d,-0.894366,-0.711111


In [423]:
df.diff() #前のデータとの差分

,one,two
a,NaN,NaN
b,5.7,NaN
c,NaN,NaN
d,NaN,NaN


In [424]:
price=pd.read_pickle("yahoo_price.pkl")

In [425]:
volume=pd.read_pickle("yahoo_volume.pkl")

In [426]:
returns=price.pct_change()

In [427]:
returns.tail()

,AAPL,GOOG,IBM,MSFT
Date,,,,
2016-10-17,-0.000680,0.001837,0.002072,-0.003483
2016-10-18,-0.000681,0.019616,-0.026168,0.007690
2016-10-19,-0.002979,0.007846,0.003583,-0.002255
2016-10-20,-0.000512,-0.005652,0.001719,-0.004867
2016-10-21,-0.003930,0.003011,-0.012474,0.042096


In [428]:
returns["MSFT"].corr(returns["IBM"])

np.float64(0.4997636114415114)

In [429]:
returns["MSFT"].cov(returns["IBM"])

np.float64(8.870655479703546e-05)

In [430]:
returns.MSFT.corr(returns.IBM)

np.float64(0.4997636114415114)

In [431]:
returns.corr()

,AAPL,GOOG,IBM,MSFT
AAPL,1.000000,0.407919,0.386817,0.389695
GOOG,0.407919,1.000000,0.405099,0.465919
IBM,0.386817,0.405099,1.000000,0.499764
MSFT,0.389695,0.465919,0.499764,1.000000


In [432]:
returns.cov()

,AAPL,GOOG,IBM,MSFT
AAPL,0.000277,0.000107,0.000078,0.000095
GOOG,0.000107,0.000251,0.000078,0.000108
IBM,0.000078,0.000078,0.000146,0.000089
MSFT,0.000095,0.000108,0.000089,0.000215


In [433]:
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [434]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [435]:
obj=pd.Series(["c","a","d","a","a","b","b","c","c"])

In [436]:
uniques=obj.unique()

In [437]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [440]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [442]:
pd.Series(obj.to_numpy()).value_counts(sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [443]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [444]:
mask=obj.isin(["b","c"])

In [445]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [446]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [447]:
to_match=pd.Series(["c","a","b","b","c","a"])

In [448]:
unique_vals=pd.Series(["c","b","a"])

In [451]:
indices=pd.Index(unique_vals).get_indexer(to_match)
#unique_valsのindexの位置を、to_matchの要素に対してそれぞれ出力

In [450]:
indices

array([0, 2, 1, 1, 0, 2])

In [452]:
data=pd.DataFrame({"Qu1":[1,3,4,3,4],
                  "Qu2":[2,3,1,2,3],
                  "Qu3":[1,5,2,4,4]})

In [453]:
data

,Qu1,Qu2,Qu3
0,1,2,1
1,3,3,5
2,4,1,2
3,3,2,4
4,4,3,4


In [454]:
data["Qu1"].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [460]:
result=data.apply(lambda col: col.value_counts()).fillna(0)

In [461]:
result

,Qu1,Qu2,Qu3
1,1.0,1.0,1.0
2,0.0,2.0,1.0
3,2.0,2.0,0.0
4,2.0,0.0,2.0
5,0.0,0.0,1.0


In [462]:
data=pd.DataFrame({"a":[1,1,1,2,2],"b":[0,0,1,0,0]})

In [463]:
data

,a,b
0,1,0
1,1,0
2,1,1
3,2,0
4,2,0


In [464]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64